# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Base URL: Set this if hosting on GitHub Pages under a project repo
# Leave empty if using a custom domain (e.g., rocasta.com)
baseurl: ""

# Site Language & Timezone
lang: en
timezone: US/Central

# SEO & Metadata
title: Rocasta Dot Com
tagline: A website created with almost no thought at all
description: >-
  A minimal, responsive, and powerful Jekyll theme for presenting professional writing.

# Change to your domain name
url: "https://www.rocasta.com"

# GitHub & Social Links
github:
  username: macdaddie

twitter:
  username: twitter_username

social:
  name: Charles Webster
  email: jekyll@rocasta.com
  links:
    - https://github.com/macdaddie
    # Uncomment to add more social links
    # - https://twitter.com/username
    # - https://www.linkedin.com/in/username

# Google Services
google_site_verification: "" # Add your Google verification string
google_analytics:
  id: "" # Add your Google Analytics ID
  pv:
    proxy_endpoint: "" # Google Analytics superProxy endpoint
    cache_path: "" # Local PV cache for users behind firewalls

# Theme Preferences
theme_mode: "" # [light | dark] - Leave empty for system preference

# Image CDN (if using external image hosting)
img_cdn: ""

# Sidebar Avatar (local or remote image URL)
avatar: ""

# Table of Contents (ToC) in posts
toc: true

# Comments Configuration
comments:
  active: "" # Options: [disqus | utterances | giscus] - Leave empty to disable
  disqus:
    shortname: "" # Your Disqus shortname
  utterances:
    repo: "" # GitHub repo for comments
    issue_term: "" # [url | pathname | title | ...]
  giscus:
    repo: "" # GitHub repo
    repo_id: ""
    category: ""
    category_id: ""
    mapping: "" # Default: 'pathname'
    input_position: "" # Default: 'bottom'
    lang: "" # Default to `site.lang`
    reactions_enabled: "" # Default: '1'

# Self-hosted static assets
assets:
  self_host:
    enabled: false # Set to true if using self-hosted assets
    env: "" # [development | production]

# Progressive Web App (PWA)
pwa:
  enabled: true

# Pagination
paginate: 10

# Code Syntax Highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections & Content Defaults
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # Applies to all files
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# Jekyll Archives (for categories & tags)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# SASS Settings (CSS compression)
sass:
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Excluded Files
exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

# AsciiDoc Support
asciidoc:
  attributes:
    showtitle: true
    icons: font

# Ensure AsciiDoc files are included in site build
include:
  - "_posts/*.adoc"
  - "_posts/*.asciidoc"
  - "*.adoc"
  - "*.asciidoc"
